# Site settings
title: Beauty Under Capitalism
email: hi@beautyundercapitalism.com
tagline: "Vote with your wallet ✌🏿✌🏾✌🏽✌🏼✌🏻"
description: Database of beauty brands founded/owned by Women of Color.
baseurl: ""
url: "https://beautyundercapitalism.com"
encoding: utf-8
lang: en
future: true

# Build settings
permalink: pretty
sass:
  sass_dir: _scss
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jemoji

# collections
collections:
  list-black:
    permalink: black-women-owned-beauty-brands
    output: true
  list-latinx:
    permalink: latina-owned-beauty-brands
    output: true
  list-mena:
    permalink: mena-owned-beauty-brands
    output: true
  list-asian:
    permalink: asian-owned-beauty-brands
    output: true
  list-problematic:
    permalink: problematic
    output: true

exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md

algolia:
  application_id: "YOUR_APP_ID"
  index_name: 'YOUR_INDEX_NAME'
  search_only_api_key: 'YOUR_SEARCH_API_KEY'